package com.pruebatecnica.leonardojpr_beetrack.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ARTICLE".
 */
@SuppressWarnings("ALL")
@Entity
public class Article implements java.io.Serializable {

    @Id(autoincrement = true)
    @Unique
    private long id;
    private String ids;
    private String name;
    private String title;
    private String author;
    private String publishedAt;
    private String description;
    private String url;
    private String urlToImage;
    private Boolean isFavorite;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Article() {
    }

    public Article(long id) {
        this.id = id;
    }

    @Generated
    public Article(long id, String ids, String name, String title, String author, String publishedAt, String description, String url, String urlToImage, Boolean isFavorite) {
        this.id = id;
        this.ids = ids;
        this.name = name;
        this.title = title;
        this.author = author;
        this.publishedAt = publishedAt;
        this.description = description;
        this.url = url;
        this.urlToImage = urlToImage;
        this.isFavorite = isFavorite;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrlToImage() {
        return urlToImage;
    }

    public void setUrlToImage(String urlToImage) {
        this.urlToImage = urlToImage;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
